<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\NewBalanceStore.Application\NewBalanceStore.Application.csproj" />
    <ProjectReference Include="..\NewBalanceStore.Infrastructure\NewBalanceStore.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseDatabase.net" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.13" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
